var goodsList = [
  {
    type: 1,
    name: "叶菜",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/bocai.jpg"),
        title: "新鲜菠菜约500g",
        desc: "新鲜带根|涮烫清炒|柔嫩多汁",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 7.99,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/leek.jpg"),
        title: "崇明韭菜350g/份",
        desc: "细嫩新韭|鲜香不辣| 适合炒食",
        detail: "本品属宽叶韭菜，辛辣味较淡,适合炒食，口感鲜甜;根部带少量泥，简单冲洗即可",
        orign: "上海市",
        condition: "冷藏",
        content: "350g",
        price: 9.89,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/cabbage.png"),
        title: "大娃娃菜(黄心)约600g",
        desc: "水嫩清甜|可炒年糕|叶片细糯",
        detail: "清甜水润味鲜美，家常鲜蔬清炒佳",
        orign: "云南省曲靖市",
        condition: "冷藏",
        content: "约600g",
        price: 5.2,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/cabbage1.png"),
        title: "有机水果甘蓝(青甘蓝)500g/份",
        desc: "果核较小|爽滑清甜| 壳薄汁多",
        detail: "鲜嫩爽口，可切丝凉拌,也可以撕片炝炒",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 9.9,
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/caixin.png"),
        title: "有机菜心250g/袋",
        desc: "适合白灼| 杆糯叶嫩|家常鲜蔬",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "云南省昆明市",
        condition: "冷藏",
        content: "500g",
        price: 8.9,
      },
    ],
  },
  {
    type: 2,
    name: "茄果瓜",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/corn.jpg"),
        title: "爆浆水果甜玉米2根500g以上",
        desc: "免煮即食|轻食佳选|多汁易爆",
        detail: "颗粒脆甜似甘蔗，可以生着啃,饱含膳食纤维",
        orign: "海南省东方市",
        condition: "冷藏",
        content: "500g以上",
        price: 14.8,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/goods2.jpg"),
        title: "日本桃太郎粉番茄600g/份",
        desc: "番茄味浓|炒蛋佳选|生熟两吃",
        detail: "日本引进品种，大小适中，沙瓤粉糯，容易出汁,适合做番茄炒蛋",
        orign: "山东省德州市",
        condition: "冷藏",
        content: "600g",
        price: 8.9,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/squash.jpg"),
        title: "西葫芦900g/份",
        desc: "可炒可汤| 柔嫩清甜|家常鲜蔬",
        detail: "柔嫩清甜，适给炒或做汤。西葫芦肉质很嫩，外表偶有运输造成的磕碰，不影响品质哦。",
        orign: "山东省潍坊市",
        condition: "冷藏",
        content: "900g",
        price: 4.99,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/pumpkin.jpg"),
        title: "惠和贝贝南瓜300g以上",
        desc: "日本品种|粉糯绵软|个头迷你",
        detail: "日本引|进品种巴掌大小，清洗蒸熟后可带皮吃，比普通南瓜更粉糯香甜",
        orign: "山东省潍坊市",
        condition: "冷藏",
        content: "300g",
        price: 7.89,
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/broccoli.jpg"),
        title: "[净菜]西兰花200g/袋",
        desc: "低卡轻蔬|补充维C|一餐刚好",
        detail: "一顿吃光小分量，盼小朵，洗洗就可就饪",
        orign: "河北",
        condition: "冷藏",
        content: "200g",
        price: 6.9,
      },
    ],
  },
  {
    type: 3,
    name: "菱白/根茎",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/sweet potato.jpg"),
        title: "胭脂红蜜薯750g/袋",
        desc: "适合蒸食|香甜粉糯红皮黄心",
        detail: "香甜粉糯，口感细腻少纤维，适合蒸食;夏季高温，需冷藏存放，收货后尽快食用",
        orign: "广东省湛江市",
        condition: "冷藏",
        content: "750g",
        price: 9.8,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/yam.jpeg"),
        title: "铁棍山药360g/份",
        desc: "带泥保鲜| 粉糯绵甜|蒸煮煲汤",
        detail: "整根铁棍山药自然生长粗细有异，不影响口感哦;夏季高温，需冷藏存放，收货后尽快食用",
        orign: "河北省保定市",
        condition: "冷藏",
        content: "360g",
        price: 9.5,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/suantai.png"),
        title: "蒜苔（白帽）300g",
        desc: "清爽脆口|辛味适中|拌炒食",
        detail: "轻掐即断，脆嫩丝滑带蒜香，微透辛味不辣口。凉拌爽口，与鸡蛋、腊肉同炒增香提味",
        orign: "山东省临沂市",
        condition: "冷藏",
        content: "300g",
        price: 5.5,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/potato.jpg"),
        title: "胶河土豆500g/份",
        desc: "口感粉糯|适合炖煮|大小均匀",
        detail: "新鲜带点土,大小均匀浑圆，方便削皮;淀粉含量高，炖煮易熟易烂，口感粉糯",
        orign: "山东省青岛市",
        condition: "冷藏",
        content: "500g",
        price: 6.8,
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/goods3.jpg"),
        title: "透心红胡萝卜400g/份",
        desc: "粗细均匀|脆嫩多汁I生熟皆可",
        detail: "粗细个头匀，取用方便好控制量",
        orign: "陕西省渭南市",
        condition: "冷藏",
        content: "400g",
        price: 6.99,
      },
    ],
  },
  {
    type: 4,
    name: "豆腐/豆制品",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/tofu1.png"),
        title: "[可即食]有豆志内酯豆腐400g/份",
        detail: "精选苏北一级大豆,适合凉拌或煮汤，豆香味浓(新老包装随机发货)",
        orign: "河北石家庄",
        condition: "冷藏",
        content: "400g",
        desc: "滑嫩细腻|适合煮汤|也能凉拌",
        price: 2.59,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/tofu2.png"),
        title: "[非转基因大豆]有豆志扬州干丝180g/份",
        detail: "本身有成味建议先置于清水中打散浸泡3.5分钟、漂洗",
        orign: "河北石家庄",
        condition: "冷藏",
        content: "180g",
        desc: "70年工艺|不易断|可拌可炒",
        price: 5.9,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/tofu3.png"),
        title: "[非转基因大豆]有豆志卤水老豆腐400g/份",
        detail: "本身有成味建议先置于清水中打散浸泡3.5分钟、漂洗",
        orign: "河北石家庄",
        condition: "冷藏",
        content: "400g",
        desc: "可汤可煎|传统点卤|不易破碎",
        price: 5.5,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/tofu4.png"),
        title: "艺杏小油豆腐130g/袋",
        desc: "绵密柔软|豆味清香|吸汁能手",
        price: 5.9,
        detail: "外酥里软有弹性，烧肉涮煮很入味;保质期较短,收到后请尽快食用哦",
        orign: "河北石家庄",
        condition: "冷藏",
        content: "130g",
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/tofu5.png"),
        title: "叮咚大满冠小油豆腐120g/袋",
        desc: "优质大豆|油脂味香|饱吸汤汁",
        detail: "非转基因大豆制作，大豆油炸过后，外皮酥软易吸汤汁",
        orign: "河北",
        condition: "冷藏",
        content: "120g",
        price: 6.8,
      },
    ],
  },
  {
    type: 5,
    name: "豆类/芽苗",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/beans1.png"),
        title: "四季豆500g/份",
        desc: "脆嫩清爽|豆荚肥厚|干煸焖烧",
        detail: "[大包装更实惠]肉质脆嫩饱满，料理前需去除筋丝,彻底熟透后再食用哦",
        orign: "江苏省苏州市",
        condition: "冷藏",
        content: "500g",
        price: 7.19,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/beans2.png"),
        title: "荷兰豆300g/份",
        desc: "新鲜脆嫩|清甜爽口|家常小炒",
        detail: "新鲜脆嫩清甜味,简单炒炒就很鲜",
        orign: "云南省保山市",
        condition: "冷藏",
        content: "300g",
        price: 7.69,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/beans3.png"),
        title: "[净菜]蔡长青手剝鲜豌豆粒150g/袋",
        detail: "新鲜剥取清香浓，烹任更省心，烹旺前建议洗净焯水",
        orign: "河北石家庄",
        condition: "冷藏",
        content: "150g",
        desc: "新鲜剥壳|洗净即烹|适合炒食",
        price: 9.9,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/beans5.png"),
        title: "有机黄豆芽200g/份",
        desc: "幼嫩鲜脆|涮锅清炒|带有机码",
        detail: "有机认证，自带有机码可扫码溯源，适合搭配肉类炒",
        orign: "江苏省泰州市",
        condition: "冷藏",
        content: "200g",
        price: 6.2,
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/beans5.png"),
        title: "[净菜]蔡长青手剝鲜豌豆粒150g/袋",
        detail: "",
        orign: "河北",
        condition: "冷藏",
        content: "150g",
        desc: "低卡轻蔬|含蛋白质|一餐刚好",
        price: 9.9,
      },
    ],
  },
  {
    type: 6,
    name: "营养菌菇",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/mushrooms1.png"),
        title: "雪榕金针菇300g",
        detail: "植物养料培育，新鲜带根，鲜香美味易烹饪(新老包装随机发货)",
        orign: "广东省惠州市",
        condition: "冷藏",
        content: "300g ",
        desc: "自然白嫩|凉拌涮烫|一餐份量",
        price: 1.89,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/mushrooms2.png"),
        title: "小平菇150g/盒",
        desc: "一份一顿|鲜嫩肥厚|火锅必备",
        detail: "一份刚好子一 餐份,小炒涮锅佳品",
        orign: "上海市",
        condition: "冷藏",
        content: "150g",
        price: 4.8,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/mushrooms.png"),
        title: "香菇200g/份",
        desc: "肉质肥厚|口感细腻|新鲜采收",
        detail: "菇肉肥厚，新鲜采收满满鲜味",
        orign: "河北省沧州市",
        condition: "冷藏",
        content: "200g",
        price: 5.9,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/mushrooms3.png"),
        title: "白蘑菇230g/份",
        desc: "带根保鲜| 拒绝漂白|可炒可烤",
        detail: "楊部菌丝乃采摘时带出，并非霉变,切除洗净即可放心",
        orign: "江苏省连云港市",
        condition: "冷藏",
        content: "230g",
        price: 5.2,
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/mushrooms4.png"),
        title: "瓶栽杳鲍菇200g/盒",
        desc: "菌体完整|菌肉肥厚| 适合炒食",
        detail: "瓶子栽培长大，菌体挺拔颜值高，菌身完整菌肉肥厚肉感足，适合炒着吃或炸着吃",
        orign: "福建省漳州市",
        condition: "冷藏",
        content: "200g",
        price: 5.8,
      },
    ],
  },
  {
    type: 7,
    name: "香辛葱蒜",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/garlic.png"),
        title: "独头蒜200g/份",
        desc: "剥皮省时|蒜味更浓|腌制调味",
        detail: "个头较小，一头只有一瓣蒜, 剥皮更省心,蒜味更浓郁",
        orign: "云南省红河哈尼族彝族自治州",
        condition: "冷藏",
        content: "200g",
        price: 11.8,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/pepper.png"),
        title: "[产地特色]宁城尖椒350g/份",
        desc: "个大肉厚I鲜香微辣|小炒拍档",
        detail: "来自内蒙古宁城县，光照充自然生长,微辣-中等辣度，小炒加点鲜香下饭",
        orign: "内蒙古自治区赤峰市",
        condition: "冷藏",
        content: "350g",
        price: 6.9,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/shallot.png"),
        title: "大葱500g/份",
        desc: "葱白粗长生吃炒食|辛香甜辣",
        detail: "新鲜带根，挺拔粗壮葱白肥，既能入菜炒食，也能做炖煮配料。",
        orign: "山东省潍坊市",
        condition: "冷藏",
        content: "500g",
        price: 3.59,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/peppercolor.png"),
        title: "红黄彩椒400g/份",
        desc: "1红1黄|炒菜配色|小炒做沙拉",
        price: 10.9,
        detail: "个头大肉嘟嘟，清甜脆嫩,配菜拌沙拉颜值高",
        orign: "山东省潍坊市",
        condition: "冷藏",
        content: "400g",
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/ginger.png"),
        title: "老姜约300g",
        desc: "辛辣味浓|去腥添香| 煲汤煮茶",
        detail: "炖肉煲汤或煮茶，去腥添香还暖胃",
        orign: "山东省临沂市",
        condition: "冷藏",
        content: "300g",
        price: 4.5,
      },
    ],
  },
  {
    type: 8,
    name: "豆类/芽苗",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/beans1.png"),
        title: "四季豆500g/份",
        desc: "脆嫩清爽|豆荚肥厚|干煸焖烧",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 7.19,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/beans2.png"),
        title: "荷兰豆300g/份",
        desc: "新鲜脆嫩|清甜爽口|家常小炒",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 7.69,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/beans3.png"),
        title: "[净菜]蔡长青手剝鲜豌豆粒150g/袋",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        desc: "新鲜剥壳|洗净即烹|适合炒食",
        price: 9.9,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/beans4.png"),
        title: "有机黄豆芽200g/份",
        desc: "幼嫩鲜脆|涮锅清炒|带有机码",
        price: 6.2,
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/beans5.png"),
        title: "[净菜]蔡长青手剝鲜豌豆粒150g/袋",
        desc: "低卡轻蔬|含蛋白质|一餐刚好",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 9.9,
      },
    ],
  },
  {
    type: 9,
    name: "营养菌菇",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/mushrooms1.png"),
        title: "雪榕金针菇300g        ",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        desc: "自然白嫩|凉拌涮烫|一餐份量",
        price: 1.89,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/mushrooms2.png"),
        title: "小平菇150g/盒",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        desc: "一份一顿|鲜嫩肥厚|火锅必备",
        price: 4.8,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/mushrooms.png"),
        title: "香菇200g/份",
        desc: "肉质肥厚|口感细腻|新鲜采收",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 5.9,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/mushrooms3.png"),
        title: "白蘑菇230g/份",
        desc: "带根保鲜| 拒绝漂白|可炒可烤",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 5.2,
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/mushrooms4.png"),
        title: "瓶栽杳鲍菇200g/盒",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        desc: "菌体完整|菌肉肥厚| 适合炒食",
        price: 5.8,
      },
    ],
  },
  {
    type: 10,
    name: "香辛葱蒜",
    info: [
      {
        id: "0",
        imgUrl: require("@/assets/img/goods/garlic.png"),
        title: "独头蒜200g/份",
        desc: "剥皮省时|蒜味更浓|腌制调味",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 11.8,
      },
      {
        id: "1",
        imgUrl: require("@/assets/img/goods/pepper.png"),
        title: "[产地特色]宁城尖椒350g/份",
        desc: "个大肉厚I鲜香微辣|小炒拍档",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 6.9,
      },
      {
        id: "2",
        imgUrl: require("@/assets/img/goods/shallot.png"),
        title: "大葱500g/份",
        desc: "葱白粗长生吃炒食|辛香甜辣",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 3.59,
      },
      {
        id: "3",
        imgUrl: require("@/assets/img/goods/peppercolor.png"),
        title: "红黄彩椒400g/份",
        desc: "1红1黄|炒菜配色|小炒做沙拉",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 10.9,
      },
      {
        id: "4",
        imgUrl: require("@/assets/img/goods/ginger.png"),
        title: "老姜约300g",
        desc: "辛辣味浓|去腥添香| 煲汤煮茶",
        detail: "家常常备时蔬，同批次产地不同，菠菜可能有大有小，敬请谅解",
        orign: "河北",
        condition: "冷藏",
        content: "250g",
        price: 4.5,
      },
    ],
  },
];

export default goodsList;
